---
# handlers file for init-totp-data

- name: restart sshd
  ansible.builtin.service: 
    name: sshd
    state: restarted

- name: restart sssd
  ansible.builtin.service: 
    name: sssd
    state: restarted

- name: set permissive selinux
  ansible.builtin.command: /usr/sbin/setenforce 0
